name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./back
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/debt-back:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./front
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/debt-front:latest

      
      - name: Configuring ssh key to connect Yandex Cloud
        uses: webfactory/ssh-agent@v0.8.0 
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 

      - name: Starting ansible deploy and transfering secrets
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
          
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml --extra-vars "target_host='${{ secrets.SERVER_IP }}' env_db_password='${{ secrets.DB_PASSWORD }}' env_jwt_secret='${{ secrets.JWT_SECRET }}'"