name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./back
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/debt-back:latest

      - name: Build and Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./front
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/debt-front:latest

      - name: Yandex Cloud CLI setup and install
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -i /home/runner/.yc -n
          
          echo "/home/runner/.yc/bin" >> $GITHUB_PATH
          
      - name: acquiring dynamic ip
        id: get_ip
        run: |
          /home/runner/.yc/bin/yc config set token ${{ secrets.YC_OAUTH_TOKEN }}
          /home/runner/.yc/bin/yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          /home/runner/.yc/bin/yc config set folder-id ${{ secrets.YC_FOLDER_ID }}
          
          VM_IP=$(/home/runner/.yc/bin/yc compute instance get compute-vm-2-1-10-hdd-1778081941293 --format json | jq -r '.network_interfaces[0].primary_v4_address.one_to_one_nat.address')
          
          echo "CURRENT_SERVER_IP=$VM_IP" >> $GITHUB_ENV
          echo "Найден актуальный IP сервера: $VM_IP"

      
      - name: Configuring ssh key to connect Yandex Cloud
        uses: webfactory/ssh-agent@v0.8.0 
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 

      - name: Starting ansible deploy and transfering secrets
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ env.CURRENT_SERVER_IP }} >> ~/.ssh/known_hosts
          
          ansible-playbook -i ansible/inventory.ini ansible/deploy.yml \
            -e "ansible_host=${{ env.CURRENT_SERVER_IP }}" \
            --extra-vars "env_db_password='${{ secrets.DB_PASSWORD }}' env_jwt_secret='${{ secrets.JWT_SECRET }}' env_grafana_password='${{ secrets.GRAFANA_PASSWORD }}'"